apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-cloud-dataflow
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    chartApiVersion: {{ .Chart.APIVersion }}
    appVersion: {{ .Chart.AppVersion }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spring-cloud-dataflow
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-cloud-dataflow
    spec:
      containers:
      - image: spring-cloud-dataflow
        name: spring-cloud-dataflow
        resources: {}
status: {}
